#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen (michael.boelen@cisofy.com), CISOfy
# Web site: https://cisofy.com
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Cryptography
#
#################################################################################
#
    InsertSection "Cryptography"
#
#################################################################################
#
    # Test        : CRYP-7902
    # Description : check for expired SSL certificates
    if [ ! -z "${OPENSSLBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no CRYP-7902 --preqs-met ${PREQS_MET} --weight L --network NO --description "Check expire date of SSL certificates"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUNDPROBLEM=0
        # Check profile for paths to check
        sSSL_PATHS=`grep "^ssl:certificates:" ${PROFILE} | cut -d ':' -f3` 
        for I in ${sSSL_PATHS}; do
            if [ -d ${I} ]; then
                FileIsReadable ${I}
                if [ ${CANREAD} -eq 1 ]; then
                    logtext "Result: found directory ${I}"
                    # Search for CRT files
                    sFINDCRTS=`find ${I} -name "*.crt" -type f -print 2> /dev/null`
                    for J in ${sFINDCRTS}; do
                        FileIsReadable ${J}
                        if [ ${CANREAD} -eq 1 ]; then
                            logtext "Test: checking certificate ${J}"
                            # Check certificate where 'end date' has been expired
                            FIND=`${OPENSSLBINARY} x509 -noout -checkend 0 -in ${J} -enddate > /dev/null ; echo $?`
                            if [ "${FIND}" = "0" ]; then
                                logtext "Result: certificate ${J} seems to be correct and still valid"
                                report "valid_certificate[]=${J}|unknown entity|"
                              else
                                FOUNDPROBLEM=1
                                logtext "Result: certificate ${J} has been expired"
                                report "expired_certificate[]=${J}|unknown entity|"
                            fi
                          else
                            logtext "Result: can not read file ${J} (no permission)"
                        fi
                    done
                  else
                    logtext "Result: can not read path ${I} (no permission)"
                fi
              else
                logtext "Result: SSL path ${I} does not exist"
            fi
        done

        if [ ${FOUNDPROBLEM} -eq 0 ]; then
            Display --indent 2 --text "- Checking SSL certificate expiration" --result OK --color GREEN
          else
            Display --indent 2 --text "- Checking SSL certificate expiration" --result WARNING --color RED
            ReportSuggestion ${TEST_NO} "Check available certificates for expiration"
        fi
    fi
#
#################################################################################
#
    # Test        : CRYP-7906
    # Description : Check old password setting restrict(add by kylin)
    Register --test-no CRYP-7906 --weight L --network NO --description "Check old passwd restrict support"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "Test: checking old passwd restrict"
        if [ -f /etc/pam.d/common-password ]; then
            logtext "Found common-password"
            FIND=`cat /etc/pam.d/common-password | grep -v "^#" |grep "pam_unix.so"| grep "remember="`
            if [ "$FIND" != "" ]; then
                logtext "Result: Found old passwd setting restrict"
                Display --indent 2 --text "- Checking old passwd restrict support" --result "ENABLE" --color GREEN
              else
                logtext "Result: Found old passwd setting restrict"
                Display --indent 2 --text "- Checking old passwd restrict support" --result "NOT ENABLE" --color WHITE
            fi
          else
            logtext "NOT found common-password"
            Display --indent 2 --text "- Checking old passwd restrict support" --result "NO CONF" --color RED
        fi
    fi
#
#################################################################################
#

wait_for_keypress

#
#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen, CISOfy - https://cisofy.com
