#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen, CISOfy (michael.boelen@cisofy.com)
# Web site: https://cisofy.com
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Unsecure services
#
#################################################################################
#
    InsertSection "Insecure services"
#
#################################################################################
#
    INETD_ACTIVE=0
    INETD_CONFIG_FILE="/etc/inetd.conf"
#
#################################################################################
#
    # Test        : INSE-8002
    # Description : Check for inetd status
    Register --test-no INSE-8002 --weight L --network NO --description "Check for enabled inet daemon"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check running processes
        logtext "Test: Searching for active inet daemon"
        IsRunning inetd
        if [ ${RUNNING} -eq 1 ]; then
            logtext "Result: inetd is running"
            Display --indent 2 --text "- Checking inetd status" --result ACTIVE --color GREEN
            INETD_ACTIVE=1
          else
            logtext "Result: inetd is NOT running"
            Display --indent 2 --text "- Checking inetd status" --result "NOT ACTIVE" --color GREEN
        fi
    fi
#
#################################################################################
#
    # Test        : INSE-8004
    # Description : Check for inetd configuration file
    if [ ${INETD_ACTIVE} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no INSE-8004 --preqs-met ${PREQS_MET} --weight L --network NO --description "Check for enabled inet daemon"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check configuration file
        logtext "Test: Searching for file ${INETD_CONFIG_FILE}"
        if [ -f ${INETD_CONFIG_FILE} ]; then
            logtext "Result: ${INETD_CONFIG_FILE} exists"
            Display --indent 4 --text "- Checking inetd.conf" --result FOUND --color WHITE
          else
            logtext "Result: ${INETD_CONFIG_FILE} does not exist"
            Display --indent 4 --text "- Checking inetd.conf" --result "NOT FOUND" --color WHITE
        fi
    fi
#
#################################################################################
#
    # Test        : INSE-8006
    # Description : Check for inetd configuration file contents if inetd is NOT active
    if [ ${INETD_ACTIVE} -eq 0 -a -f ${INETD_CONFIG_FILE} ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no INSE-8006 --preqs-met ${PREQS_MET} --weight L --network NO --description "Check configuration of inetd when disabled"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Check if any service is enabled in /etc/inetd.conf (inetd is not active, see test 8002)
        logtext "Test: check if all services are disabled if inetd is disabled"
        FIND=`cat ${INETD_CONFIG_FILE} | grep -v "^#" | grep -v "^$"`
        if [ "${FIND}" = "" ]; then
            Display --indent 4 --text "- Checking inetd.conf services" --result OK --color GREEN
          else
            Display --indent 4 --text "- Checking inetd.conf services" --result SUGGESTION --color YELLOW
            ReportSuggestion ${TEST_NO} "Although inetd is not running, make sure no services are enabled in ${INETD_CONFIG_FILE}"
        fi
    fi
#
#################################################################################
#
    # Test        : INSE-8016
    # Description : Check for telnet enabled via inetd
    if [ ${INETD_ACTIVE} -eq 1 -a -f ${INETD_CONFIG_FILE} ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no INSE-8016 --preqs-met ${PREQS_MET} --weight L --network NO --description "Check for telnet via inetd"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "Test: checking telnet presence in inetd configuration"
        FIND=`grep "^telnet" ${INETD_CONFIG_FILE}`
        if [ "${FIND}" = "" ]; then
            logtext "Result: telnet not enabled in ${INETD_CONFIG_FILE}"
            Display --indent 2 --text "- Checking inetd (telnet)" --result "NOT FOUND" --color GREEN
            AddHP 3 3
          else
            logtext "Result: telnet enabled in ${INETD_CONFIG_FILE}"
            Display --indent 2 --text "- Checking inetd (telnet)" --result WARNING --color RED
            ReportSuggestion "${TEST_NO}" "Disable telnet in inetd configuration and use SSH instead"
            AddHP 1 3
        fi
    fi
#
#################################################################################
#
    # Test        : INSE-8018
    # Description : Check for telnet presence(add by kylin)
Register --test-no INSE-8018 --weight L --network NO --description "Check for telnet presence"
if [ ${SKIPTEST} -eq 0 ]; then
        logtext "Test: checking telnet presence in system"
        FIND=`dpkg -l | grep "ii  telnet"`
        if [ "$FIND" = "" ]; then
            logtext "Result: telnet not enabled in system"
            Display --indent 2 --text "- Checking telnet presence" --result "NOT FOUND" --color GREEN
            AddHP 3 3
          else
            logtext "Result: telnet enabled in system"
            Display --indent 2 --text "- Checking telnet presence" --result WARNING --color RED
            ReportSuggestion "${TEST_NO}" "Remove telnet in system and use SSH instead"
            AddHP 1 3
        fi
fi
#
#################################################################################
#
    # Test        : INSE-8020
    # Description : Check for ftpd presence(add by kylin)
Register --test-no INSE-8020 --weight L --network NO --description "Check for ftpd presence"
if [ ${SKIPTEST} -eq 0 ]; then
    logtext "Test: checking ftpd presence in system"
    FIND=`dpkg -l | grep "ii  ftp"`
    if [ "$FIND" = "" ]; then
        logtext "Result: ftp not enabled in system"
        Display --indent 2 --text "- Checking ftp presence" --result "NOT FOUND" --color GREEN
        AddHP 2 2
      else
        logtext "Result: ftp enabled in system"
        Display --indent 2 --text "- Checking ftp presence" --result WARNING --color RED
        ReportSuggestion "${TEST_NO}" "Remove ftp in system"
        AddHP 1 2
    fi
fi
#
#################################################################################
#
    # Test        : INSE-8022
    # Description : Check for snmp presence(add by kylin)
Register --test-no INSE-8022 --weight L --network NO --description "Check for snmpd presence"
if [ ${SKIPTEST} -eq 0 ]; then
    logtext "Test: checking snmp presence in system"
    FIND=`dpkg -l | grep "ii  snmp"`
    if [ "$FIND" = "" ]; then
        logtext "Result: snmp not enabled in system"
        Display --indent 2 --text "- Checking snmp presence" --result "NOT FOUND" --color GREEN
        AddHP 2 2
      else
        logtext "Result: snmp enabled in system"
        Display --indent 2 --text "- Checking snmp presence" --result WARNING --color RED
        ReportSuggestion "${TEST_NO}" "Remove snmp in system"
        AddHP 1 2
    fi
fi
#
#################################################################################
#
    # Test        : INSE-8024
    # Description : Check anonymous enable for vsftpd(add by kylin)
Register --test-no INSE-8024 --weight L --network NO --description "Check anonymous enable for vsftpd"
if [ ${SKIPTEST} -eq 0 ]; then
    logtext "Test: checking anonymous enable for vsftpd"
    if [ -f /etc/vsftpd.conf ]; then
        FIND=`cat /etc/vsftpd.conf | grep -v "^#" | grep "anonymous_enable=" | awk -F= '{ print $2 }'`
        if [ "$FIND" = "YES" ]; then
            logtext "Result: vsftpd anonymous user is enabled"
            Display --indent 2 --text "- Checking vsftpd anonymous" --result "ENABLE" --color RED
          else
            logtext "Result: vsftpd anonymous user is not enabled"
            Display --indent 2 --text "- Checking vsftpd anonymous" --result "NOT ENABLE" --color GREEN
        fi
      else
        logtext "Result: vsftpd conf not found"
            Display --indent 2 --text "- Checking vsftpd anonymous" --result "NO CONF" --color WHITE
    fi
fi
#
#################################################################################
#

wait_for_keypress

#
#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen, CISOfy - https://cisofy.com
